spring:
  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/tribal}
    username: postgres
    password: password
    continueOnError: true
  flyway:
    enabled: true
    locations: classpath:/db/scripts/migration